name: gsa_tools_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=25.4.0
  - backports.zstd=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - exceptiongroup=1.3.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.2
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.3.5
  - openssl=3.6.0
  - outcome=1.3.0.post0
  - packaging=25.0
  - pandas=2.3.3
  - pip=25.3
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.14.2
  - python-chromedriver-binary=145.0.7573.0.0
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.5
  - selenium=4.39.0
  - selenium-manager=4.39.0
  - six=1.17.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - tk=8.6.13
  - tqdm=4.67.1
  - trio=0.32.0
  - trio-websocket=0.12.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - webdriver-manager=4.0.2
  - websocket-client=1.9.0
  - wsproto=1.3.2
  - zstd=1.5.7
